#!/bin/bash

echo "🎯 Points Shop - Quick Demo Setup"
echo "================================="
echo ""
echo "This is a full-stack employee recognition and rewards platform!"
echo ""
echo "📋 What's included:"
echo "✅ React + TypeScript frontend"
echo "✅ Node.js + Express backend"
echo "✅ PostgreSQL database with Drizzle ORM"
echo "✅ JWT authentication"
echo "✅ Point system with peer recognition"
echo "✅ Rewards shop for redeeming points"
echo "✅ Mood tracking and analytics"
echo "✅ Complete transaction history"
echo ""
echo "🚀 To get started:"
echo ""
echo "1. Install PostgreSQL:"
echo "   macOS: brew install postgresql && brew services start postgresql"
echo "   Ubuntu: sudo apt-get install postgresql postgresql-contrib"
echo "   Windows: Download from postgresql.org"
echo ""
echo "2. Create database:"
echo "   createdb points_shop"
echo ""
echo "3. Install dependencies:"
echo "   npm install"
echo "   cd server && npm install"
echo ""
echo "4. Setup database:"
echo "   cd server"
echo "   npm run db:generate"
echo "   npm run db:migrate" 
echo "   npm run db:seed"
echo ""
echo "5. Start servers:"
echo "   # Terminal 1: cd server && npm run dev"
echo "   # Terminal 2: npm run dev"
echo ""
echo "6. Login with demo account:"
echo "   Email: zeann.palma@company.com"
echo "   Password: password123"
echo ""
echo "📖 See README.md for complete setup instructions"
echo ""
echo "🎉 Features you can test:"
echo "   • Send points to colleagues"
echo "   • Browse and purchase rewards"
echo "   • Track your mood daily"
echo "   • View transaction history"
echo "   • Update your profile"
