#!/bin/bash

# Create points_shop database setup script

echo "Points Shop Database Setup"
echo "=========================="
echo ""
echo "Since Docker is not available, you can manually set up PostgreSQL by:"
echo ""
echo "1. Install PostgreSQL locally:"
echo "   - macOS: brew install postgresql"
echo "   - Ubuntu/Debian: sudo apt-get install postgresql postgresql-contrib"
echo "   - Windows: Download from https://www.postgresql.org/download/"
echo ""
echo "2. Start PostgreSQL service:"
echo "   - macOS: brew services start postgresql"
echo "   - Ubuntu/Debian: sudo service postgresql start"
echo "   - Windows: Use Services panel or pg_ctl"
echo ""
echo "3. Create database and user:"
echo "   sudo -u postgres psql"
echo "   CREATE DATABASE points_shop;"
echo "   CREATE USER postgres WITH ENCRYPTED PASSWORD 'password';"
echo "   GRANT ALL PRIVILEGES ON DATABASE points_shop TO postgres;"
echo "   \\q"
echo ""
echo "4. Set up database schema:"
echo "   cd server"
echo "   npm run db:migrate"
echo "   npm run db:seed"
echo ""
echo "5. Start the servers:"
echo "   # Terminal 1 - Backend"
echo "   cd server && npm run dev"
echo ""
echo "   # Terminal 2 - Frontend"
echo "   npm run dev"
echo ""
echo "The application will be available at:"
echo "- Frontend: http://localhost:5173"
echo "- Backend API: http://localhost:3001"
echo ""
